Remove redundant code, minor cleanups, style fixes
GrapheneOS/Camera pull request #142
Opened 2022-03-07 05:19 UTC by Zanthed

2022-03-24 03:47 UTC, anonlatte requested changes

2022-03-24 03:47 UTC, anonlatte commented on app/src/main/java/app/grapheneos/camera/ui/activities/MoreSettings.kt
>          snackBar = Snackbar.make(
IMO would be better make variable nullable and init it at `fun showMessage`

2022-03-24 03:47 UTC, anonlatte commented on app/src/main/java/app/grapheneos/camera/ui/activities/MoreSettings.kt
> +
extract to another function like `initInputFields`
probably you may find another functionality which may be added there

2022-03-26 01:08 UTC, closed without merging

2022-03-26 01:09 UTC, Zanthed commented on app/src/main/java/app/grapheneos/camera/CamConfig.kt
> +    return try {
This is a temporary workaround for a CameraX bug that doesn't properly handle extensions so I think we'll instead remove it in the next CameraX release assuming they fix it.