Add Dark Theme to the QR results Dialog box.
GrapheneOS/Camera pull request #172
Opened 2022-04-07 07:34 UTC by ExypnosPrincess

2022-04-07 12:10 UTC, flawedworld commented on app/src/main/java/app/grapheneos/camera/ui/activities/MainActivity.kt
> +            /*dialog.window?.setBackgroundDrawable(
Please remove commented code

2022-04-07 15:57 UTC, Zanthed commented
Squash the 2 commits into 1 commit

2022-04-08 22:21 UTC, MHShetty commented
Hey @ExypnosPrincess,

We might need to make some minor color changes before/after we merge this PR to make it more consistent with the current default theme (for e.g. the result region shading, brighten/whitening of the current result mode) and possibly brighten the copy-to-clipboard and share icon (as they currently look a bit dull in dark theme). I'll merge the PR and make the required changes as soon as I get a more clear idea about this.

Thanks a lot for taking efforts and making this pull request!

Regards,
Mohit

2022-04-09 03:15 UTC, ExypnosPrincess commented
Thank you @MHShetty  for your kind reply. I welcome the changes and am aware my initial attempt needed improvements, but wasn't fully sure how to best go forward with them as I am still learning android development at this moment. Thank very much for accepting my changes.

2022-04-09 12:30 UTC, ExypnosPrincess commented
Thank you @MHShetty for your kind and informative reply.

2022-04-09 15:55 UTC, smdyv requested changes
The result could look like this:

![result-light](https://user-images.githubusercontent.com/88971341/162581613-97ad0bc4-1325-407b-b6ed-fc2fd4cc1f24.png)
![result-dark](https://user-images.githubusercontent.com/88971341/162581618-dc0ee43c-2370-4e73-823c-954da329f766.png)

2022-04-09 15:55 UTC, smdyv commented on app/src/main/res/layout/scan_result_dialog.xml
> +        android:textColor="@color/qr_results"/>
This view inherits colors for the text color, so no custom color is needed. If we want a more prominent color than the default, we can use `?android:attr/textColorPrimary`, which is the most prominent text color and a [night-qualified color resource](https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#themes-styles).

```suggestion
        android:textColor="?android:attr/textColorPrimary"/>
```

2022-04-09 15:55 UTC, smdyv commented on app/src/main/res/layout/scan_result_dialog.xml
> -        android:background="@drawable/qr_result_background"
It has already been expressed by @MHShetty that we want to keep a "box" for the result.

My suggestion:
1. Keep this line.
2. Define a new color element (e.g. `qr_result_background`) with the value of:
    - default: @color/material_dynamic_neutral90
    - night: @color/material_dynamic_neutral20
4. Go to `drawables/qr_result_background.xml` and use the newly defined color resource for the color value (e.g. `@color/qr_result_background`).

2022-04-10 09:26 UTC, ExypnosPrincess commented
Thank so much, @smdyv for taking the time out of your day to explain to me how I could improve my code. I really appreciate it.

2022-04-10 10:53 UTC, MHShetty commented
> The result could look like this:
> 
> ![result-light](https://user-images.githubusercontent.com/88971341/162581613-97ad0bc4-1325-407b-b6ed-fc2fd4cc1f24.png) ![result-dark](https://user-images.githubusercontent.com/88971341/162581618-dc0ee43c-2370-4e73-823c-954da329f766.png)

Hey @smdyv,

The new dark theme color combination suggested by you not only looks consistent with the default theme, but also looks really neat and pretty!

Thanks a lot for helping us make this feature better 😊

Regards,
Mohit

2022-04-10 10:58 UTC, ExypnosPrincess commented
> > The result could look like this:
> > ![result-light](https://user-images.githubusercontent.com/88971341/162581613-97ad0bc4-1325-407b-b6ed-fc2fd4cc1f24.png) ![result-dark](https://user-images.githubusercontent.com/88971341/162581618-dc0ee43c-2370-4e73-823c-954da329f766.png)
> 
> Hey @smdyv,
> 
> The new dark theme color combination suggested by you not only looks consistent with the default theme, but also looks really neat and pretty!
> 
> Thanks a lot for helping us make this feature better 😊
> 
> Regards, Mohit

I must agree. It does look really pretty. I'm happy they suggested those changes.

2022-04-10 11:05 UTC, merged

2022-04-10 11:13 UTC, MHShetty commented
Hey @ExypnosPrincess,

The PR has now been merged to the main branch of our repository. 

Thanks a lot for making this pull request @ExypnosPrincess and @smdyv for those beautiful recommendations!

2022-04-10 11:29 UTC, ExypnosPrincess commented
You are very welcome, @MHShetty.